### ISSUE TITLE
请问你是直接在linux下编写，还是先在windows上学习，再移植到linux

### ISSUE THREAD

**Issue by kaoxirui** [SuycxZMZ/CChat#1]

**Comment by SuycxZMZ** [comment]
我自己的学习过程是现在windows下抄了一份代码，因为我之前的项目也没用windows做过，踩踩坑学习一下。不过你要是不想踩坑，按我写的样子直接写linux的也行，比windows坑少多了


来自 MEIZU 20 Pro

-------- 原始邮件 --------
发件人：kaoxirui ***@***.***>
时间：2024年11月29日 10:12
收件人：SuycxZMZ/CChat ***@***.***>
抄送：Subscribed ***@***.***>
主题：[SuycxZMZ/CChat] 请问你是直接在linux下编写，还是先在windows上学习，再移植到linux (Issue #1)

**Comment by kaoxirui** [comment]
请问是从头开始抄吗，大概用了多少时间

**Comment by SuycxZMZ** [comment]
我是看了作者的几个视频，把项目结构看清楚开始从头抄的。因为我c++包括c的socketapi，和asio都比较熟悉，抄起来比较快，一周多一点抄完windows的，移植调通花了两天。qt界面我做一半放弃了，没什么审美，我直接用的作者原版克隆下来的


来自 MEIZU 20 Pro

-------- 原始邮件 --------
发件人：kaoxirui ***@***.***>
时间：2024年11月29日 10:22
收件人：SuycxZMZ/CChat ***@***.***>
抄送：SuycxZMZ ***@***.***>,Comment ***@***.***>
主题：Re: [SuycxZMZ/CChat] 请问你是直接在linux下编写，还是先在windows上学习，再移植到linux (Issue #1)

**Comment by kaoxirui** [comment]
socket编程和asio有什么学习推荐吗

**Comment by SuycxZMZ** [comment]
推荐统一在linux下编写和调试


来自 MEIZU 20 Pro

-------- 原始邮件 --------
发件人：kaoxirui ***@***.***>
时间：2024年11月30日 19:43
收件人：SuycxZMZ/CChat ***@***.***>
抄送：SuycxZMZ ***@***.***>,Comment ***@***.***>
主题：Re: [SuycxZMZ/CChat] 请问你是直接在linux下编写，还是先在windows上学习，再移植到linux (Issue #1)
